name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: buildjet-4vcpu-ubuntu-2204-arm

    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag europe-west4-docker.pkg.dev/impl-383520/docker/appsource:latest

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v1.1.1
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: "Configure docker"
        run: |
          gcloud auth configure-docker europe-west4-docker.pkg.dev

      - name: "Push image to GCR"
        run: |
          docker push europe-west4-docker.pkg.dev/impl-383520/docker/appsource:latest

      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get pods

      # - name: "rollout"
      #   run: |
      #     kubectl rollout restart deployment  -n appsource  appsource
          