name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: buildjet-4vcpu-ubuntu-2204-arm

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . -q --file Dockerfile --tag europe-west4-docker.pkg.dev/impl-383520/docker/appsource:latest --build-arg GITHUB_SHA=${GITHUB_SHA}

      - id: gcp_auth
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v2.1.0
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: "Configure docker"
        run: |
          gcloud auth configure-docker europe-west4-docker.pkg.dev

      - name: "Push image to GCR"
        run: |
          docker push -q europe-west4-docker.pkg.dev/impl-383520/docker/appsource:latest

      - name: "Rollout restart"
        env:
          KBCONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          echo "${KBCONFIG}" > /tmp/kube_config
          ls -la /tmp
          export KUBECONFIG=/tmp/kube_config
          kubectl --insecure-skip-tls-verify rollout restart deployment -n appsource appsource
