name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: buildjet-4vcpu-ubuntu-2204-arm

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . -q --file Dockerfile --tag europe-west4-docker.pkg.dev/impl-383520/docker/appsource:latest --build-arg GITHUB_SHA=${GITHUB_SHA}

      - id: gcp_auth
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v1.1.1
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: "Configure docker"
        run: |
          gcloud auth configure-docker europe-west4-docker.pkg.dev

      - name: "Push image to GCR"
        run: |
          docker push -q europe-west4-docker.pkg.dev/impl-383520/docker/appsource:latest

      - id: install_kubectl
        name: "Install kubectl"
        uses: azure/setup-kubectl@v3

      - name: "Configure kubectl"
        uses: azure/k8s-set-context@v3
        with:
           method: kubeconfig
           kubeconfig:  ${{ secrets.KUBE_CONFIG }}

      - name: "Rollout restart"
        run: |
          kubectl --insecure-skip-tls-verify rollout restart deployment -n appsource appsource
          
